// LOCALHOST
###
GET http://localhost:8080/contacts/632ee164ccf17c0650f431d8 HTTP/1.1


###
### 

POST   http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json


{"firstname":"Anesu",
    "lastname":"Mvududu",
    
    "email":"anehangwa@gmail",
    "favcolor":"black",
    "birthday":"22 september 2022"}




###

PUT  http://localhost:8080/contacts/"632ee05551101789d79ffb2fHTTP/1.1

Content-Type: application/json

{"firstname":"Anesu",
    "lastname":"Mvududu",
    
    "email":"anesuhangwa@gmail",
    "favcolor":"grey",
    "birthday":"22 september 2022"}



### 

DELETE  http://localhost:8080/contacts/632c3a9838f1fabc3f00bdab HTTP/1.1

###

GET   https://cse341-anesu.herokuapp.com/632c3668ee0f552991d6575c